### ISSUE TITLE
Crash when adding numpy array in data

### ISSUE THREAD

**Issue by duboism** [dotsdl/datreant#20] opened 2015-09-22 10:07 UTC
I have cloned `datreant` yesterday in order to give it a try (I'm up-to-date with this repository). The following script exits with a segfault:

    import datreant
    import numpy as np
    sprout = datreant.Treant('sprout')
    print "Adding list"
    sprout.data.add('test', [1, 2, 3])
    print "Adding np.array"
    sprout.data.add('test2', np.array([1, 2, 3]))
Adding the list works but adding the `np.array` fails in `H5Open`. If I re-run the script without removing the `sprout` directory, it works.
I use Ubuntu 14.04. The current version of the HDF5 library is 1.8.11.

**Comment by duboism** [comment] 2015-09-22 12:52
Using pdb, I discovered that the crash occurs in file h5py/_hl/files.py line 88:

    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
Seems related to `h5py` and in turn to `libhdf5` (note that I used synaptic to install it).

**Comment by dotsdl** [comment] 2015-09-22 17:40
Hi @duboism, I'm working on a release, but are you using the `master` branch or the `develop` branch? I've just merged `develop` into `master`, so let me know if this changes things on your end. I'm giving your script a try with the commit `master` was pointing to now.

**Comment by duboism** [comment] 2015-09-22 20:35
Hi @dotsdl , I was using the `master` branch. I have tried with `develop` (and an up-to-date `master`). The first run of the script fails but now the second fails too. Can you confirm this?

**Comment by dotsdl** [comment] 2015-09-22 21:36
@duboism I'll try reproducing these problems on an Ubuntu machine. Travelling at the moment, but I think I can have an answer later today. Thanks for sharing this!

**Comment by dotsdl** [comment] 2015-09-23 04:20
@duboism I've reproduced the problem, but now working on a solution.

**Comment by duboism** [comment] 2015-09-23 08:25
@dotsdl Great! Don't hesitate to notify me for testing.

**Comment by duboism** [comment] 2015-09-24 07:42
By the way, installing `datreant` only install the `egg` file (a zip file containing the code and the `egg-info` dir). This complicates debugging because (AFAIK) `pdb` can't inspect the code. Other packages install the code and the `egg-info` directory directly (without zipping them). Is there a way to install `datreant` this way?

**Comment by dotsdl** [comment] 2015-09-25 23:07
@duboism installing `datreant` with

    setup.py install

(optionally with the `--user` flag to install locally in `~/.local`) will give a compressed zip file. To install the package in a way that makes it easy to debug, install with:

    setup.py develop

(also optionally with the `--user` flag to install locally). This will install a link to your development tree instead of a compressed egg, and you can work in your development tree and see the changes reflected in your imports of the module.

Does that help? Btw, the segmentation fault occurs in `datreant.persistence.npDataFile._open_file_w`, but calling the contents of the function:

    h5py.File('testfile.h5', 'a')

in isolation does not result in a segfault. I've heard that use of both PyTables and h5py in the same python session can result in weird behavior, but importing both and opening and closing file handles does not generally result in a segfault on my end (although I managed to get one to happen once, but can't get it to happen again).

Also, strangely, I can't reproduce this problem on other machines also running Ubuntu 14.04. I'm really scratching my head on this one.

I have a band-aid fix that does appear to work, however. Basically, opening up an `h5py` file for writing in `'w'` mode, overwriting the whole file instead of just overwriting an internal node, appears to work without a segfault on my test machine. Does this work for you? The [h5pysegfault](https://github.com/dotsdl/datreant/tree/h5pysegfaultfix) branch features this change.

**Comment by dotsdl** [comment] 2015-10-10 19:59
Wow...I just noticed that I never actually pushed the change to that branch. Apologies on my end. Does this fix the problem on your end?

**Comment by duboism** [comment] 2015-10-13 15:06
@dotsdl Sorry I was working on something else. I have installed the h5pysegfault and the simple test script works now.

**Closed** 2015-10-18 22:22 UTC

**Comment by dotsdl** [comment] 2015-10-18 22:27
@duboism good to hear! I just merged and pushed this to `develop`.
